version: "2"

linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: standard
  enable:
    - gosec
    - perfsprint
    - gocritic
  disable:
    - gochecknoinits
    - depguard
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

issues:
  fix: true