// Code generated by hookr-gen. DO NOT EDIT.
// Source schema: ./testdata/contracts/greeter/greeter.proto

package greeterprotocontract

type Method struct {
	ID           uint32
	Name         string
	RequestType  string
	ResponseType string
}

const (
	ContractName                = "Greeter"
	ContractCodec               = "protobuf"
	SchemaHashHex               = "88c8d892a88c6c74c4e7bbcec864bbe035ef18090d038408c93d435a0f9f82d8"
	MethodHello          uint32 = 2814245639
	CapabilityHello      uint64 = uint64(1) << 0
	ContractCapabilities uint64 = CapabilityHello
)

var Methods = []Method{
	{ID: MethodHello, Name: "Hello", RequestType: "HelloRequest", ResponseType: "HelloResponse"},
}
