// Code generated by hookr-gen. DO NOT EDIT.
//go:build wasip1

package greeterprotocontract

import (
	"errors"
	"fmt"

	"github.com/mopeyjellyfish/hookr/pdk"
	pdkcontract "github.com/mopeyjellyfish/hookr/pdk/contract"
)

var pdkSchemaHash = [pdkcontract.SchemaHashLen]byte{
	136,
	200,
	216,
	146,
	168,
	140,
	108,
	116,
	196,
	231,
	187,
	206,
	200,
	100,
	187,
	224,
	53,
	239,
	24,
	9,
	13,
	3,
	132,
	8,
	201,
	61,
	67,
	90,
	15,
	159,
	130,
	216,
}

func PDKHandshake() pdkcontract.Handshake {
	hs := pdkcontract.NewHandshake(pdkSchemaHash)
	hs.Capabilities = ContractCapabilities
	return hs
}

func EnablePDKHandshake() {
	pdkcontract.EnableHandshakeWithCapabilities(pdkSchemaHash, ContractCapabilities)
}

func PDKSchema() pdkcontract.Schema {
	return pdkcontract.Schema{
		Name:         ContractName,
		SchemaHash:   pdkSchemaHash,
		Capabilities: ContractCapabilities,
		Methods: []pdkcontract.Method{
			{
				ID:           pdkcontract.MethodID(MethodHello),
				Name:         "Hello",
				RequestType:  "HelloRequest",
				ResponseType: "HelloResponse",
			},
		},
	}
}
func BindPluginMethodHello[Req any, Resp any](
	decodeReq pdkcontract.Decoder[Req],
	encodeResp pdkcontract.Encoder[Resp],
	fn func(req Req) (Resp, error),
) func([]byte) ([]byte, error) {
	return pdkcontract.BindPluginMethod(decodeReq, encodeResp, fn)
}

func RegisterPluginMethodHello[Req any, Resp any](
	decodeReq pdkcontract.Decoder[Req],
	encodeResp pdkcontract.Encoder[Resp],
	fn func(req Req) (Resp, error),
) {
	pdk.FnMethod(MethodHello, pdkcontract.BindPluginMethod(decodeReq, encodeResp, fn))
}

func CallHostMethodHello[Req any, Resp any](
	req Req,
	encodeReq pdkcontract.Encoder[Req],
	decodeResp pdkcontract.Decoder[Resp],
) (Resp, error) {
	var zero Resp
	payload, err := encodeReq(req)
	if err != nil {
		return zero, err
	}
	data, err := pdk.HostCallMethod(MethodHello, payload)
	if err != nil {
		return zero, err
	}
	return decodeResp(data)
}

type PluginMethodHandlers struct {
	MethodHello func(payload []byte) ([]byte, error)
}

func SetPluginMethodDispatcher(h PluginMethodHandlers) {
	pdk.SetMethodDispatcher(func(methodID uint32, payload []byte) ([]byte, error) {
		switch methodID {
		case MethodHello:
			if h.MethodHello == nil {
				return nil, errors.New("plugin handler MethodHello is nil")
			}
			return h.MethodHello(payload)
		default:
			return nil, fmt.Errorf("unknown method id %d", methodID)
		}
	})
}
