// Code generated by hookr-gen. DO NOT EDIT.
//go:build !wasip1

package greeterprotocontract

import (
	"context"
	"errors"
	"fmt"

	hookrruntime "github.com/mopeyjellyfish/hookr/runtime"
	runtimecontract "github.com/mopeyjellyfish/hookr/runtime/contract"
	"github.com/mopeyjellyfish/hookr/runtime/module"
)

var runtimeSchemaHash = [runtimecontract.SchemaHashLen]byte{
	136,
	200,
	216,
	146,
	168,
	140,
	108,
	116,
	196,
	231,
	187,
	206,
	200,
	100,
	187,
	224,
	53,
	239,
	24,
	9,
	13,
	3,
	132,
	8,
	201,
	61,
	67,
	90,
	15,
	159,
	130,
	216,
}

func RuntimeHandshake() runtimecontract.Handshake {
	hs := runtimecontract.NewHandshake(runtimeSchemaHash)
	hs.Capabilities = ContractCapabilities
	return hs
}

func RuntimeSchema() runtimecontract.Schema {
	return runtimecontract.Schema{
		Name:         ContractName,
		SchemaHash:   runtimeSchemaHash,
		Capabilities: ContractCapabilities,
		Methods: []runtimecontract.Method{
			{
				ID:           runtimecontract.MethodID(MethodHello),
				Name:         "Hello",
				RequestType:  "HelloRequest",
				ResponseType: "HelloResponse",
			},
		},
	}
}

type RuntimeMethodHandlers struct {
	MethodHello func(ctx context.Context, payload []byte) ([]byte, error)
}

func RuntimeCallHandlerV2(h RuntimeMethodHandlers) module.CallHandlerV2 {
	return func(ctx context.Context, methodID uint32, payload []byte) ([]byte, error) {
		switch methodID {
		case MethodHello:
			if h.MethodHello == nil {
				return nil, errors.New("runtime handler MethodHello is nil")
			}
			return h.MethodHello(ctx, payload)
		default:
			return nil, fmt.Errorf("unknown method id %d", methodID)
		}
	}
}
func BindRuntimeMethodHello[Req any, Resp any](
	decodeReq runtimecontract.Decoder[Req],
	encodeResp runtimecontract.Encoder[Resp],
	fn func(ctx context.Context, req Req) (Resp, error),
) func(context.Context, []byte) ([]byte, error) {
	return runtimecontract.BindHostMethod(decodeReq, encodeResp, fn)
}

func HostMethodHello[Req any, Resp any](
	decodeReq runtimecontract.Decoder[Req],
	encodeResp runtimecontract.Encoder[Resp],
	fn func(ctx context.Context, req Req) (Resp, error),
) hookrruntime.HostMethod {
	return hookrruntime.HostFnMethod(MethodHello, runtimecontract.BindHostMethod(decodeReq, encodeResp, fn))
}

func CallPluginMethodHello[Req any, Resp any](
	ctx context.Context,
	rt *hookrruntime.Runtime,
	req Req,
	encodeReq runtimecontract.Encoder[Req],
	decodeResp runtimecontract.Decoder[Resp],
) (Resp, error) {
	var zero Resp
	payload, err := encodeReq(req)
	if err != nil {
		return zero, err
	}
	fn, err := hookrruntime.PluginFnMethod(rt, MethodHello)
	if err != nil {
		return zero, err
	}
	data, err := fn.Call(ctx, payload)
	if err != nil {
		return zero, err
	}
	return decodeResp(data)
}
