on:
  push:
    branches:
      - main
  pull_request:

name: Lint
jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Tidy
        run: make tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          args: --timeout=5m ./host/...
