name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.26.x']
        os: [ ubuntu-latest ]
    name: ${{ matrix.os }} Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mopeyjellyfish/hookr
